### DISCUSSION TITLE
Custom workflows

### DISCUSSION THREAD

**Discussion by giovannibaratta** [bitmagnet-io/bitmagnet#434] [Q&A] [answered]
Hello,

I am struggling with the configuration of a custom workflow.

I have defined a classifier in this way following the documentation https://bitmagnet.io/guides/classifier.html

```yaml
classifier:
  flags:
    delete_content_types:
      - comic
      - software
      - xxx
  workflow: delete-archive
```

Then I tried to define the workflow but it's not clear if the `workflows` keywork is a top-level keyword or if it's nested under the classifier (looking at the JSON schema it should be nested).

```yaml
workflows:
  delete-archive:
    - run_workflow: default
```

Regardless of where I put the `workflows` I get the following error `panic: default workflow 'delete-archive' not found`.

If I set the workflow to the default ( `workflow: default` ) in the classifier and I inspect the classifier configuration with the CLI, the `delete-archive` workflow in not present in the configuration.

I am not sure if this is relevant, but I am loading the configuration using `EXTRA_CONFIG_FILES`
