### ISSUE TITLE
Make a spot for config.yml in your minimum docker-compose.yml

### ISSUE THREAD

**Issue by EntityinArray** [bitmagnet-io/bitmagnet#286]
- [X] I have checked the existing issues to avoid duplicates
- [X] I have redacted any info hashes and content metadata from any logs or screenshots attached to this issue

### Is your feature request related to a problem? Please describe

Wiki says that configuration is done with config.yml in current directory.
In your minimum docker-compose.yml in [Installation](https://bitmagnet.io/setup/installation.html), bitmagnet service has no pwd.
The only current way to configure dockerized bitmagnet out of the box is through env vars

### Describe the solution you'd like

Add a volume for storing the config.yml file in your docker-compose.yml

**Comment by EntityinArray** [comment]
For anyone facing the same issue, here's my docker-compose.yml
```
services:
  bitmagnet:
    image: ghcr.io/bitmagnet-io/bitmagnet:latest
    container_name: bitmagnet
    volumes:
      # Mount config, make this ootb
      - ./config:/root/.config/bitmagnet
    ports:
      # API and WebUI port:
      - "3333:3333"
      # BitTorrent ports:
      - "3334:3334/tcp"
      - "3334:3334/udp"
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
    #      - TMDB_API_KEY=your_api_key
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      # disable the next line to run without DHT crawler
      - --keys=dht_crawler
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: bitmagnet-postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    #    ports:
    #      - "5432:5432" Expose this port if you'd like to dig around in the database
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bitmagnet
      - PGUSER=postgres
    shm_size: 1g
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      start_period: 20s
      interval: 10s

```
