### ISSUE TITLE
Database connection drops continuously (0.9.3)

### ISSUE THREAD

**Issue by cianiandreadev** [bitmagnet-io/bitmagnet#287]
- [x] I have checked the existing issues to avoid duplicates
- [x] I have redacted any info hashes and content metadata from any logs or screenshots attached to this issue

### Describe the bug

After migrating to 0.9.3 I noticed very high cpu load on postgres.
Checking the logs I noticed the connection between postgres and bitmagnet continuously drops and restart.

I tried to reboot multiple times but did not help.

Migrations are completed according to Bitmagnet log.

### Environment Information (Required)

- Bitmagnet version: `[0.9.3]`
- OS and version: `[Docker]`

### Additional context

These are the logs:
```
2024-06-27 10:23:33.115 UTC [8656] ERROR:  canceling statement due to user request
2024-06-27 10:23:33.115 UTC [8656] STATEMENT:  SELECT EXISTS(SELECT * FROM "content" WHERE "content"."type" = 'movie' AND ("content"."release_date" >= '2015-01-01 00:00:00' AND "content"."release_date" < '2016-01-01 00:00:00') AND content.tsv @@ '800 <-> words'::tsquery)
2024-06-27 10:23:33.116 UTC [8656] LOG:  could not send data to client: Connection reset by peer
2024-06-27 10:23:33.116 UTC [8656] FATAL:  connection to client lost
2024-06-27 10:23:33.136 UTC [8677] ERROR:  canceling statement due to user request
```

I noticed that the Statement change, but the error is repeated at every different statement.

**Comment by mgdigital** [comment]
> After migrating to 0.9.3 I noticed very high cpu load on postgres.

Hi, please see the release note for 0.9.0 and the re-index required for ordering. The queue needs to work through all existing torrents to add missing fields. This did cause performance issues for some users which are mitigated by reducing the queue concurrency. Letting the queue work down will allow load to return to normal (or clearing it altogether, but then your ordering won't fully work). Can I ask about your hardware setup and specifically the disk that the DB is running on? It's recommended to run the database on a fast SSD.

**Comment by cianiandreadev** [comment]
Hi @mgdigital , 
Thanks for the support

The machine has the following specs (no docker restrictions are applied)

CPU: Intel i5-6400 @ 2.7GHz
RAM: 64GB
SSD: Crucial_CT480M500SSD1 

This issue is running since ~ 16h

Number of entries in bitmagnet (taken by opening the webinterface and read the ALL count) `All ~14,527,984`

**Comment by cianiandreadev** [comment]
If this can help, here you can find the Grafana charts for Bitmagnet.
We can clearly see the spike of CPU usage (and Disk I/O indeed) after the update.

What still is not clear (even if the db is re-indexing) is WHY the connection drop error in the logs.

<img width="1240" alt="Screenshot 2024-06-27 at 13 50 24" src="https://github.com/bitmagnet-io/bitmagnet/assets/1215511/8c259d82-0c38-4237-b66c-37f7f2cfc8e0">

**Comment by mgdigital** [comment]
Hi, do you have any failed jobs (in your `queue_jobs` table), and if so what are the error messages? Note if you see any "missing <n> info hashes" these are to be expected and will be silenced in a future release. If you don't see any errors aside from that then as far as Bitmagnet is concerned "everything is fine". While there have been a few teething issues with this queue job, they seem to be resolved for most users and this is the first I've heard of anyone having dropped connections - you may have some mileage in tweaking your Postgres config, increasing the memory available to it etc...

**Comment by mgdigital** [comment]
This should do it:

```
SELECT error FROM queue_jobs WHERE status = 'failed' LIMIT 100;
```

**Comment by mgdigital** [comment]
> I will try to leave the container running for another day

If you have 15 million torrents this would take (in normal conditions) a couple of days for the full reindex queue to work down, but much longer if you're experiencing I/O issues.

**Comment by DerBunteBall** [comment]
Die you change the docker-compose file?

Set the PosgreSQL shm_size to 2GB für the start. Normally this houldn't lead to some RAM consume.

I have in a peak (with imports) shitty I/O and poorer CPU max 2,8GB total memory usage on the system.

**Comment by cianiandreadev** [comment]
> This should do it:
> 
> ```
> SELECT error FROM queue_jobs WHERE status = 'failed' LIMIT 100;
> ```

Thank you very much:

The output seems optimistic:

```
bitmagnet=# SELECT error FROM queue_jobs WHERE status = 'failed' LIMIT 100;
 error 
-------
(0 rows)
```

**Comment by cianiandreadev** [comment]
> Die you change the docker-compose file?
> 
> Set the PosgreSQL shm_size to 2GB für the start. Normally this houldn't lead to some RAM consume.
> 
> I have in a peak (with imports) shitty I/O and poorer CPU max 2,8GB total memory usage on the system.

Hi @DerBunteBall , 
The docker-compose file has the following:

```yml
  postgres:
    image: postgres:16.0-alpine
    container_name: bitmagnet-postgres
    volumes:
      - ${ROOT}/data/postgres:/var/lib/postgresql/data
    #    ports:
    #      - "5432:5432" Expose this port if you'd like to dig around in the database
    restart: unless-stopped

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - POSTGRES_PASSWORD=******
      - POSTGRES_DB=bitmagnet
      - PGUSER=postgres
    shm_size: 1g
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      start_period: 20s
      interval: 10s
```
