### ISSUE TITLE
The DHT component is abnormal.

### ISSUE THREAD

**Issue by 648480505** [bitmagnet-io/bitmagnet#398]
- [√] I have checked the existing issues to avoid duplicates
- [√ ] I have redacted any info hashes and content metadata from any logs or screenshots attached to this issue

### Describe the bug

The reason for the DHT query error is that the DHT bootstrap nodes are resolved to IPv6 addresses and queries are made, and Docker for Windows does not have IPv6 enabled by default. An effective and quick way to enable IPv6 is as follows:

1. Open Docker Desktop and click the settings button. Go to the Resources tab ---- Network - ✔ Enable the host network and apply the changes.

2. In the `docker-compose.yml` file, add the `network_mode: "host"` configuration to each service.
```yaml
bitmagnet:
    image: ghcr.io/bitmagnet - io/bitmagnet:latest
    container_name: bitmagnet
    ports:
      # API and WebUI port:
      - "3333:3333"
      # BitTorrent ports:
      - "3334:3334/tcp"
      - "3334:3334/udp"
    network_mode: "host"
```
3. When using the host mode, the container service name cannot be resolved. When connecting to the database, the service name cannot be used for the address. Instead, "localhost" or "127.0.0.1" should be used.

restart: unless-stopped
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PASSWORD=postgres
      - TMDB_ENABLED=false 
4. Run `docker-compose up -d`. 

### To Reproduce

1. run
2. wait for a period of time
3. The DHT component is abnormal.
4. Restart the Docker Desktop, and the DHT component becomes normal. 

### Expected behavior

1. run
2. The DHT component keeps running stably. 

### Environment Information (Required)

- Bitmagnet version: `[0.10.0]`
- OS and version: `[windows 10 x64]`
- Browser and version (if issue is with WebUI): `[e.g. Chrome 117.0.5938.149]`
- Please specify any config values for which you have overridden the defaults: `(e.g. dht_crawler.save_pieces: true)`
