### ISSUE TITLE
Hope to support proxy settings within the container

### ISSUE THREAD

**Issue by A13788899580** [bitmagnet-io/bitmagnet#428]
After deployment, DHT is in a closed state;
After reading the document, I guess it's a network issue in China, so I need to go through an agent.

**Comment by DerBunteBall** [comment]
Bitmagnet does not support proxy settings.

The included docker-compose.yml uses GlueTUN to work via a VPN.

This should solve the problem, provided you have a VPN that is not affected by filtering.

Blocking P2P technologies is quite common, even in other countries.

**Comment by A13788899580** [comment]
> Bitmagnet does not support proxy settings.Bitmagnet 不支持代理设置。
> 
> The included docker-compose.yml uses GlueTUN to work via a VPN.包含的 docker-compose.yml 使用 GlueTUN 通过 VPN 工作。
> 
> This should solve the problem, provided you have a VPN that is not affected by filtering.这应该可以解决问题，前提是您的 VPN 不受过滤的影响。
> 
> Blocking P2P technologies is quite common, even in other countries.阻止 P2P 技术非常普遍，即使在其他国家也是如此。

I found that it doesn't need to be so complicated, GlueTUN is not required, just add the local proxy address in the environment to work properly, for example: ALL-PROXY: socks 5://127.0.0.1:20173, as long as the local proxy works normally.

**Comment by A13788899580** [comment]
![Image](https://github.com/user-attachments/assets/710d697e-11b2-4b16-a9be-e88352bc1836)

**Comment by A13788899580** [comment]
> Bitmagnet does not support proxy settings.Bitmagnet 不支持代理设置。
> 
> The included docker-compose.yml uses GlueTUN to work via a VPN.包含的 docker-compose.yml 使用 GlueTUN 通过 VPN 工作。
> 
> This should solve the problem, provided you have a VPN that is not affected by filtering.这应该可以解决问题，前提是您的 VPN 不受过滤的影响。
> 
> Blocking P2P technologies is quite common, even in other countries.阻止 P2P 技术非常普遍，即使在其他国家也是如此。

In addition, whether the payment platform supporting the project can support WeChat or Alipay.

**Comment by A13788899580** [comment]
> > > Bitmagnet does not support proxy settings.Bitmagnet 不支持代理设置。Bitmagnet 不支持代理设置。
> > > The included docker-compose.yml uses GlueTUN to work via a VPN.包含的 docker-compose.yml 使用 GlueTUN 通过 VPN 工作。包含的 docker-compose.yml 使用 GlueTUN 通过 VPN 工作。
> > > This should solve the problem, provided you have a VPN that is not affected by filtering.这应该可以解决问题，前提是您的 VPN 不受过滤的影响。这应该可以解决问题，前提是您的 VPN 不受过滤的影响。
> > > Blocking P2P technologies is quite common, even in other countries.阻止 P2P 技术非常普遍，即使在其他国家也是如此。阻止 P2P 技术非常普遍，即使在其他国家也是如此。
> > 
> > 
> > I found that it doesn't need to be so complicated, GlueTUN is not required, just add the local proxy address in the environment to work properly, for example: ALL-PROXY: socks 5://127.0.0.1:20173, as long as the local proxy works normally.我发现这并不需要如此复杂，GlueTUN 并非必需，只需在环境中添加本地代理地址即可正常工作，例如：ALL-PROXY: socks 5://127.0.0.1:20173，只要本地代理能够正常工作即可。
> 
> Can u show the detail of the proxy u set, i set the proxy in the docker-compose file like the followings,你能展示一下你设置的代理的详细信息吗？我在 docker-compose 文件中设置了代理，如下所示，
> 
> ```
> services:
>   bitmagnet:
>      image: xxx
>      environment:
>       - ALL_PROXY=socks5://user:pass@192.168.1.1:111
> ```
> 
> but i failed, the log shows:但我失败了，日志显示：
> 
> ```
> v2@v2.16.5/request.go:1045      Get "https://api.themoviedb.org/3/authentication?api_key=xxx": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
> ```
> 
> and i could access themoviedb in the shell with curl. what happened ?而且我可以在 shell 中使用 curl 访问 themoviedb。发生了什么？
================================  
> My environment settings are as follows:
   environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres
      TMDB_API_KEY: XXXXXX  # 取消注释并填写你的 API 密钥
      ALL_PROXY: socks5://127.0.0.1:20173
> If your PROXY is functioning as described in the log, should you fill in TMDB_API_KEY in Compose？

**Comment by backups4me** [comment]
the proxy vars works as followings:
```
services:
  bitmagnet:
     environment: 
       - HTTP_PROXY=http://xxx:xxx@192.168.1.1:8000
       - HTTPS_PROXY=http://xxx:xxx@192.168.1.1:8000
```

**Comment by SjoerdV** [comment]
> the proxy vars works as followings:
> 
> ```
> services:
>   bitmagnet:
>      environment: 
>        - HTTP_PROXY=http://xxx:xxx@192.168.1.1:8000
>        - HTTPS_PROXY=http://xxx:xxx@192.168.1.1:8000
> ```

Sadly this is not working as advertised. The system-wide or service/user specific proxy is not respected by bitmagnet (in the latest version to date 0.10)  -> and probably never will <-. All the DHT connections are made 'directly'. Maybe the proxy is only used for the TMDB stuff, because I can see a single connection through my proxy from the bitmagnet process. Maybe someone can get some clarity on this?

After some searching I found the reason for the proxy not working for DHT as follows (very old source, but it seems nothing has really changed since 2014 https://forums.torguard.net/index.php?/topic/294-disable-dht-and-udp-trackers/):

> SOCKS/HTTP proxy servers only support outgoing TCP connections. Incoming connections and UDP will not be affected by these settings.
> You should turn off DHT and disable UDP tracker connections if you are using a SOCKS/HTTP proxy to conceal your true IP address.

What you need to know is that all DHT request from bitmagnet start out as outgoing UDP packets so they will not be proxy-ed by most proxies. If the author has any remarks, please do.

**Comment by acme64** [comment]
i'm naive to how this works, but i had an idea of routing the dht traffic through a socks5 setup, is that what this thread is related to?

from what i understand the recommended method of routing the container through a vpn means all traffic, even the prowlarr integration would have to route through the VPN as well no? or can that still happen locally

**Comment by Apollo3zehn** [comment]
If you use docker or podman you can use gluetun for the torrent traffic and still connect prowlarr to bitmagnet via port publishing. The idea is to first create a gluetun container and then create the bitmagnet container and make it use the gluetun network (VPN). When the gluetun container also publishes the bitmagnet port, bitmagnet can be accessed from the docker / podman host and other containers normally, without VPN. Example:

```
# gluetun publishes the bitmagnet port
gluetun:
      name: gluetun
      image: docker.io/qmcgaw/gluetun:v3.41
      capabilities:
        - CAP_NET_ADMIN
      device:
        - "/dev/net/tun:/dev/net/tun"
      ports:
        - "0.0.0.0:8013:8013" # qbittorrent
        - "0.0.0.0:8018:3333" # bitmagnet
        - "0.0.0.0:5432:5432" # bitmagnet-postgres
      env:
        - ...

...
# bitmagnet uses the gluetun network
bitmagnet:
      name: bitmagnet
      image: ghcr.io/bitmagnet-io/bitmagnet:v0.10
      network: "container:gluetun"
      volumes:
        ...

...
# nothing special configured here
prowlarr:
      name: prowlarr
      image: lscr.io/linuxserver/prowlarr:latest
      volumes:
```

*Note that the config above is not a docker-compose format but very similar and the ports shown are for my specific setup. It is a podman setup, I hope it works similar for Docker.*

Prowlarr can now access bitmagnet via the published port.
