### ISSUE TITLE
[Feature Request] crawl through the onion network to prevent abuse reports

### ISSUE THREAD

**Issue by Motophan** [bitmagnet-io/bitmagnet#65]
**Have you checked the roadmap on the website, and existing issues, before opening a dupllcate issue?**
Yes

**Is your feature request related to a problem? Please describe.**
If you run this program you will start to show up in iknowwhatyoudownload.com and could potentially start receiving abuse reports. 

**Describe the solution you'd like**
Let us route everything through tor if we want to, disabled by default. Make sure dns is proxied to prevent rdns leakage. Either a docker-compose tor container or system level tor service and have this container route through it either via the socks5 proxy on localhost, or just let us have a enviroment variable that is respected, like
`SOCKS_PROXY=127.0.0.1:9050`

```
services:
  bitmagnet:
    build:
      context: .
    container_name: bitmagnet
    #     image: ghcr.io/bitmagnet-io/bitmagnet:latest
    volumes:
      - ./data/bitmagnet:/tmp
    #ports:
      #- "3333:3333"
      # BitTorrent ports, wont work
      #- "3334:3334/tcp"
      #- "3334:3334/udp"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_ADDR=redis:6379
      - SOCKS_PROXY=127.0.0.1:9050
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      - --keys=dht_crawler
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
```

**Describe alternatives you've considered**
I figured out how to route this over a vpn but not over tor. What I did was 
1) create a wireguard container with mullvad
2) set this container as "network mode container" and the container the wireguard mullvad container
However you cannot expose ports. 

**Additional context**
Im not sure open ports are needed other than performance as the other end would need an open port to serve metainfo to us. If I need to run this for a few months thats fine. 

tldr; I want to run the crawler through tor.
